name: master

on: [push, pull_request]

jobs:
  master:
    runs-on: ubuntu-latest
          
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
          
      - name: Install Package Requirements
        run: pip install wheel twine coverage
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Install Build Requirements
        run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Unit Tests
        run: coverage run -m unittest tests/test_mockend.py; coverage xml

      - name: Codacy Coverage
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml -t ${{ secrets.CODACY_TOKEN }}
