name: release

on: [release]

jobs:
  test:
    runs-on: ubuntu-latest
          
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          
      - name: Install Package Requirements
        run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Install Build Requirements
        run: pip install wheel twine coverage
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Unit Tests
        run: coverage run -m unittest tests/mockend.py; coverage xml

      - name: Publish Package
        run: |
          python3 setup.py sdist bdist_wheel
          twine check dist/*
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
